# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_tZUQmPdOt0sEsxr34_QLzDQI6JoibAS
"""

import streamlit as st
import pandas as pd
import re
import nltk
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB

# Download necessary data
nltk.download('stopwords')
stop_words = set(stopwords.words('english'))

# --- 1. CLEANING FUNCTION (From your model) ---
def clean_text(text):
    text = str(text).lower()
    text = re.sub(r'http\S+|www\S+|https\S+', '', text)
    text = re.sub(r'[^a-zA-Z\s]', '', text)
    text = re.sub(r'\s+', ' ', text).strip()
    words = text.split()
    words = [word for word in words if word not in stop_words]
    return " ".join(words)

# --- 2. MODEL INITIALIZATION ---
# Since we need to run without a backend file, we train a quick classifier on load
# using the logic established in your notebook.
@st.cache_resource
def load_model():
    # Load your dataset (Ensure 'Project file.csv' is in the same folder)
    df = pd.read_csv('Project file.csv')
    df = df[['class', 'message']].dropna()
    df['clean_message'] = df['message'].apply(clean_text)
    df['label'] = df['class'].map({'valid': 0, 'spam': 1})

    # TF-IDF
    tfidf = TfidfVectorizer(max_features=3000)
    X = tfidf.fit_transform(df['clean_message'])
    y = df['label']

    # Simple Classifier (Matching your Analytics course standards)
    model = MultinomialNB()
    model.fit(X, y)
    return tfidf, model

# --- 3. STREAMLIT UI ---
st.set_page_config(page_title="Email Spam Classifier", page_icon="📧")

st.title("📧 Email Spam Detector")
st.markdown("Enter an email message below to check if it is **Spam** or **Valid**.")

tfidf, model = load_model()

# User Input
user_input = st.text_area("Email Content:", placeholder="Type or paste email text here...", height=200)

if st.button("Analyze Email"):
    if user_input.strip() == "":
        st.warning("Please enter some text first.")
    else:
        # Process input
        cleaned = clean_text(user_input)
        vectorized = tfidf.transform([cleaned])

        # Predict
        prediction = model.predict(vectorized)
        probability = model.predict_proba(vectorized)

        # Display Result
        st.divider()
        if prediction[0] == 1:
            st.error(f"### Result: SPAM")
            st.write(f"Confidence: {probability[0][1]:.2%}")
        else:
            st.success(f"### Result: VALID (Ham)")
            st.write(f"Confidence: {probability[0][0]:.2%}")

# Footer
st.sidebar.info("Model built for MIS 542: Advanced Business Analytics.")